name: CI
on: [push]
jobs:
  build:
    name: Build, Lint, & Test Project
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} & setup the .npmrc file to publish to npm
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linter
        run: yarn lint
      - name: Run tests
        run: yarn jest --coverage
      - name: Read code coverage value
        id: coverage
        run: echo "::set-output name=coverage::$(cat coverage/coverage-summary.json | jq .total.statements.pct)"
  coverage:
    name: Generate Coverage Badge
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update code coverage badge
        run: curl -I "https://badges.zoostage.com/zoocasa/node-data/${GITHUB_REF##*/}.svg?token=$BADGE_API_KEY&coverage=${{ needs.build.outputs.coverage }}"
        env:
          GITHUB_REF: ${{ secrets.GITHUB_REF }}
          BADGE_API_KEY: ${{ secrets.BADGE_API_KEY}}
